In [2]:
import numpy as np

In [3]:
temp_list = [185.5, 186.2, 184.8, 185.0, 186.1]

In [4]:
temps = np.array(temp_list)

In [5]:
temps

array([185.5, 186.2, 184.8, 185. , 186.1])

In [6]:
temps.mean()

np.float64(185.52)

In [7]:
sensor_list = [[185.5, 186.2, 184.8], [120.3, 121.5, 119.8], [45.2, 44.8, 45.5]]

In [8]:
sensor_data = np.array(sensor_list)

In [9]:
sensor_data

array([[185.5, 186.2, 184.8],
       [120.3, 121.5, 119.8],
       [ 45.2,  44.8,  45.5]])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((3, 4), dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [12]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [14]:
np.full((2, 5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [15]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [19]:
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [20]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.linspace(0, 10, 5, endpoint=False)

array([0., 2., 4., 6., 8.])

In [22]:
np.linspace(0, 24, 25)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [23]:
### 랜덤 데이터 생성

In [24]:
# 0 ~ 1 사이의 균등 분포로 랜덤숫자 만들기

In [25]:
np.random.seed(20)

In [26]:
np.random.rand(5)

array([0.5881308 , 0.89771373, 0.89153073, 0.81583748, 0.03588959])

In [27]:
np.random.rand(5)

array([0.69175758, 0.37868094, 0.51851095, 0.65795147, 0.19385022])

In [28]:
np.random.rand(5)

array([0.2723164 , 0.71860593, 0.78300361, 0.85032764, 0.77524489])

In [29]:
np.random.rand(3, 4)

array([[0.03666431, 0.11669374, 0.7512807 , 0.23921822],
       [0.25480601, 0.85762553, 0.94977903, 0.56168686],
       [0.17878052, 0.77025193, 0.49238104, 0.63125307]])

In [30]:
np.random.randint(1, 6, (4, 3))

array([[2, 1, 4],
       [1, 3, 3],
       [4, 4, 1],
       [3, 2, 3]], dtype=int32)

In [31]:
# 키 평균 170, 표준편차 5

In [32]:
np.random.normal(loc=170, scale=10, size=10)

array([179.85851217, 155.27375983, 151.26000244, 175.93433302,
       155.33558738, 163.62851044, 158.31088645, 172.84103841,
       181.87989095, 173.5780685 ])

In [33]:
np.random.normal(loc=170, scale=10, size=(3, 4))

array([[174.83570468, 162.90830348, 183.88116082, 165.44962235],
       [175.82383646, 176.18822645, 187.2222527 , 179.66258167],
       [160.45490512, 188.81296958, 173.50412358, 207.79890753]])

In [34]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [35]:
arr = np.array(np.arange(5))

In [36]:
np.random.shuffle(arr)

In [37]:
arr

array([2, 4, 3, 0, 1])

In [38]:
arr.size

5

In [39]:
np.random.choice(arr, arr.size)

array([1, 2, 1, 4, 4])

In [40]:
# 단위행렬 => 대각선의 값이 1인 것, 나머지는 0
# 3 * 1 = 3

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
# 대각행렬 만들기

In [43]:
np.diag([5, 1, 2, 9])

array([[5, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 9]])

In [44]:
temps

array([185.5, 186.2, 184.8, 185. , 186.1])

In [45]:
temps.shape

(5,)

In [46]:
sensor_data.shape

(3, 3)

In [47]:
temps.ndim

1

In [48]:
sensor_data.ndim

2

In [49]:
temps.size

5

In [50]:
sensor_data.size

9

In [51]:
temps.dtype

dtype('float64')

In [52]:
sensor_data.dtype

dtype('float64')

In [53]:
temps[-1]

np.float64(186.1)

In [54]:
temps[1:3 + 1]

array([186.2, 184.8, 185. ])

In [55]:
sensor_data

array([[185.5, 186.2, 184.8],
       [120.3, 121.5, 119.8],
       [ 45.2,  44.8,  45.5]])

In [56]:
sensor_data[0, 2]

np.float64(184.8)

In [57]:
sensor_data[[0, 2]]

array([[185.5, 186.2, 184.8],
       [ 45.2,  44.8,  45.5]])

In [58]:
sensor_data[1, ]

array([120.3, 121.5, 119.8])

In [59]:
sensor_data[1, [0, 2]]

array([120.3, 119.8])

In [60]:
sensor_data[:2, 2]

array([184.8, 119.8])

In [61]:
sensor_data[[0, 2], ]

array([[185.5, 186.2, 184.8],
       [ 45.2,  44.8,  45.5]])

In [62]:
sensor_data[: , [0, 2]]

array([[185.5, 184.8],
       [120.3, 119.8],
       [ 45.2,  45.5]])

In [63]:
# Boolean Indexing

In [64]:
temps

array([185.5, 186.2, 184.8, 185. , 186.1])

In [65]:
temps > 186

array([False,  True, False, False,  True])

In [66]:
temps

array([185.5, 186.2, 184.8, 185. , 186.1])

In [74]:
(temps < 185) | (temps > 186)

array([False,  True,  True, False,  True])

In [75]:
temps[(temps < 185) | (temps > 186)]

array([186.2, 184.8, 186.1])

In [77]:
(temps >= 185) & (temps <= 186)

array([ True, False, False,  True, False])

In [78]:
temps[(temps >= 185) & (temps <= 186)]

array([185.5, 185. ])

In [79]:
temps[3] = 185.3

In [80]:
temps

array([185.5, 186.2, 184.8, 185.3, 186.1])

In [82]:
temps[1:4] = [186.5, 184.5, 185.5]

In [83]:
temps

array([185.5, 186.5, 184.5, 185.5, 186.1])

In [84]:
temps[1:4] = 0

In [85]:
temps

array([185.5,   0. ,   0. ,   0. , 186.1])

In [86]:
x = np.random.randint(0, 100, 20)

In [87]:
x

array([27, 39, 87,  9, 14, 31, 56, 56, 58, 79, 27, 50, 74, 69,  2, 57, 23,
       95, 25, 41], dtype=int32)

In [89]:
# 정상 범위: 20 ~ 85, 이상치는 모두 0으로 변경

In [95]:
x[(x < 20) | (x > 85)] = 0

In [97]:
x

array([27, 39,  0,  0,  0, 31, 56, 56, 58, 79, 27, 50, 74, 69,  0, 57, 23,
        0, 25, 41], dtype=int32)

In [98]:
np.nan

nan

In [107]:
x = x.astype(np.float64)

In [108]:
x

array([27., 39.,  0.,  0.,  0., 31., 56., 56., 58., 79., 27., 50., 74.,
       69.,  0., 57., 23.,  0., 25., 41.])

In [109]:
x[(x < 20) | (x > 85)] = np.nan

In [110]:
x

array([27., 39., nan, nan, nan, 31., 56., 56., 58., 79., 27., 50., 74.,
       69., nan, 57., 23., nan, 25., 41.])

In [111]:
# 이상치를 평균값으로 변경

In [112]:
x = np.random.randint(0, 100, 20)

In [113]:
x

array([ 9, 66, 15, 65, 30, 88, 49, 40, 11, 69,  0, 58, 86, 37, 68, 18,  9,
       57, 14, 35], dtype=int32)

In [114]:
x[(x < 20) | (x > 85)] = x.mean()

In [115]:
x

array([41, 66, 41, 65, 30, 41, 49, 40, 41, 69, 41, 58, 41, 37, 68, 41, 41,
       57, 41, 35], dtype=int32)

In [140]:
x.argmin()

np.int64(4)

In [121]:
x.mean()

np.float64(47.15)

In [122]:
x.std()

np.float64(11.705874593553443)

In [132]:
X = np.random.randint(0, 100, (5, 5))

In [133]:
X

array([[55, 65, 82, 51, 12],
       [36, 41, 74, 96, 95],
       [85, 31, 67, 76, 42],
       [ 2, 39, 96, 86, 79],
       [ 7, 11, 85, 27, 71]], dtype=int32)

In [134]:
X.min()

np.int32(2)

In [135]:
X.max()

np.int32(96)

In [136]:
X.mean()

np.float64(56.44)

In [137]:
X.std()

np.float64(29.34904427745476)

In [138]:
X.sum()

np.int64(1411)

In [139]:
X.argmax()

np.int64(8)

In [143]:
X.max(axis=1)

array([82, 96, 85, 96, 85], dtype=int32)

In [144]:
X

array([[55, 65, 82, 51, 12],
       [36, 41, 74, 96, 95],
       [85, 31, 67, 76, 42],
       [ 2, 39, 96, 86, 79],
       [ 7, 11, 85, 27, 71]], dtype=int32)

In [148]:
x

array([41, 66, 41, 65, 30, 41, 49, 40, 41, 69, 41, 58, 41, 37, 68, 41, 41,
       57, 41, 35], dtype=int32)

In [147]:
sum(x > 60)

np.int64(4)

In [149]:
# 사분위수

In [150]:
data = [5, 4, 1, 9, 3, 2, 2]

In [151]:
sorted(data)

[1, 2, 2, 3, 4, 5, 9]

In [152]:
np.median(data)

np.float64(3.0)

In [153]:
np.percentile(data, 50)

np.float64(3.0)

In [154]:
np.percentile(data, 25)

np.float64(2.0)

In [155]:
np.percentile(data, 75)

np.float64(4.5)

In [156]:
np.percentile(data, [25, 50, 75])

array([2. , 3. , 4.5])

In [157]:
# Q1, Q2, Q3

In [158]:
# 이상치 탐지(IQR 방법)

In [170]:
data = np.array([185, 186, 184, 250, 183, 187, 50, 185, 186, 184])

In [171]:
q1 = np.percentile(data, 25)

In [172]:
q3 = np.percentile(data, 75)

In [173]:
iqr = q3 - q1

In [174]:
lower_bound = q1 - 1.5*iqr
upper_bound = q3 + 1.5*iqr

In [175]:
data[(data < lower_bound) | (data > upper_bound)]

array([250,  50])